// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ForceSend$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ForceSend";
  readonly sourceName: "contracts/ForceSend.sol";
  readonly abi: [{"inputs":[],"stateMutability":"payable","type":"constructor"},{"inputs":[{"internalType":"address payable","name":"recipient","type":"address"}],"name":"destroy","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x608060405261010d806100115f395ff3fe6080604052348015600e575f5ffd5b50600436106025575f3560e01c8062f55d9d146029575b5f5ffd5b603f6004803603810190603b919060b1565b6041565b005b8073ffffffffffffffffffffffffffffffffffffffff16ff5b5f5ffd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f608582605e565b9050919050565b609381607d565b8114609c575f5ffd5b50565b5f8135905060ab81608c565b92915050565b5f6020828403121560c35760c2605a565b5b5f60ce84828501609f565b9150509291505056fea2646970667358221220c017e7d12a10fa4dd9b18328a6e0f278767447babf8c91b83df4e7e47fe4662464736f6c63430008220033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106025575f3560e01c8062f55d9d146029575b5f5ffd5b603f6004803603810190603b919060b1565b6041565b005b8073ffffffffffffffffffffffffffffffffffffffff16ff5b5f5ffd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f608582605e565b9050919050565b609381607d565b8114609c575f5ffd5b50565b5f8135905060ab81608c565b92915050565b5f6020828403121560c35760c2605a565b5b5f60ce84828501609f565b9150509291505056fea2646970667358221220c017e7d12a10fa4dd9b18328a6e0f278767447babf8c91b83df4e7e47fe4662464736f6c63430008220033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ForceSend.sol";
  readonly buildInfoId: "solc-0_8_34-44db86875b6c1c081cdb0b30d2645f2ddc48bb67";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ForceSend"]: ForceSend$Type;
    ["contracts/ForceSend.sol:ForceSend"]: ForceSend$Type;
  }
}